# Stripe
stripe.secret-key=sk_test_51TL63e5YPiCbqm3s9UIs9U52psQqvtRM2ul5m7O5lTwRYBNgTrLcPCzCwveZf25T0ZA5Dygi7XobnfjYU3uTuXgu00AQDYlAfe
stripe.publishable-key=pk_test_51TL63e5YPiCbqm3slONd2HAVc0qbHH7RTG7CCnDrSp39dEkf4B82TZG9ILER2fOrSP5SXj7hNO19hIrkxFIRaJfp00Ygz05Xuw

# Stripe
# Webhook secret Local
# fournit par la commande : stripe listen --forward-to localhost:8080/payments/webhook
stripe.webhook-secret=whsec_660327e7f09583365135e400a7a5c1d68721c6c1a597ec613835219c2e250c88